config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "cocktails#index"

  resources :cocktails do
    resources :doses, only: [:new, :create]
    collection do
      get :search
    end
  end

  delete "doses/:id", to: "doses#destroy", as: :dose_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :picture
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, :uniqueness => { :scope => :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @ingredients = Ingredient.all
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new()
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def search

    @cocktails  = []
    @query = params[:query]


    @ingredient = Ingredient.find_by_name(@query)
    if !@ingredient.nil?
      @doses = Dose.where(ingredient_id: @ingredient.id)
      @doses.each do |dose|
        @cocktails << Cocktail.find(dose.cocktail_id)
      end

    end

  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end


  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.delete

    redirect_to root_path
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def update
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new()
  end

  def create
    @cocktail = Cocktail.find(params["cocktail_id"])
    @dose = Dose.create(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end

  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <h1> Edit <%=  @cocktail.name %> </h1>
  <%= simple_form_for :cocktail, method: :patch do |f| %>
    <%= f.input :name %>
    <%= f.input :picture, as: :file %>
    <%= f.submit "Edit cocktail", :class => "btn btn-flat"  %>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.makemycocktail.com/images/Cocktail_Banner.jpg);">
  <div class="container">
    <h1>Cocktail Generator</h1>
    <p>Add your favorites cocktails and become the best cocktail designer!</p>
    <div>
    <%= link_to "Generate a cocktail", new_cocktail_path, :class => "btn btn-flat" %>
    </div>
    <div class= "search-input">
      <form novalidate="novalidate" class="simple_form search" action="cocktails/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="query" id="search_query" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i> Search for a cocktail
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="container">
  <center> <h1>My cocktail list</h1> </center>
  <div class="cards">
    <% @cocktails.each do |cocktail| %>

      <% if cocktail.picture.attached? %>

      <a href= <%= "cocktails/#{cocktail.id}" %> >
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.picture.key, crop: :fill %>)">
          <%= cocktail.name %>
        </div>
      </a>
      <% else %>
      <a href= <%= "cocktails/#{cocktail.id}" %> >
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg')">
          <%= cocktail.name %>
        </div>
      </a>
      <% end %>

    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1> Add a new cocktail </h1>
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add a new cocktail", :class => "btn btn-flat"  %>
  <% end %>
</div>

app/views/cocktails/search.html.erb
<div class="container">
  <% if @cocktails == [] %>

  <center> <h1>Sorry, no result found for <%= @query %> </h1> </center>
  <% else %>

   <center> <h1>Search results <%= @query %> </h1> </center>
  <% end %>
  <div class="cards">
    <% @cocktails.each do |cocktail| %>

      <% if cocktail.picture.attached? %>

      <a href= <%= "cocktails/#{cocktail.id}" %> >
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.picture.key, crop: :fill %>)">
          <%= cocktail.name %>
        </div>
      </a>
      <% else %>
      <a href= <%= "cocktails/#{cocktail.id}" %> >
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg')">
          <%= cocktail.name %>
        </div>
      </a>
      <% end %>

    <% end %>

  </div>
  <center> <%= link_to "Back to cocktail list", cocktails_path, :class => "back" %> </center>

</div>

app/views/cocktails/show.html.erb
<div class="container">

  <div class="card-show">
    <div>
      <h2> Ingredient List for <%=  @cocktail.name %> </h2>


        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li> <%= "#{dose.ingredient.name} : #{dose.description}" %>  <%= link_to "Delete" , dose_delete_path(dose), method: :delete %></li>

          <% end %>
        </ul>

      <%= link_to "Add Dose" , new_cocktail_dose_path(@cocktail), :class => "btn btn-primary" %>

    </div>
    <% if @cocktail.picture.attached? %>
    <div>
      <%= cl_image_tag @cocktail.picture.key, crop: :fill %>
    </div>
    <% end %>
  </div>

  <div class="edit-options">
    <%= link_to "Edit " , edit_cocktail_path(@cocktail), :class => "btn btn-primary" %>
    <%= link_to "Delete " , cocktail_path, method: :delete, :class => "btn btn-danger" %>
  </div>




</div>

app/views/doses/new.html.erb
<div class="container">
  <h1> Add a new ingredient to <%=  @cocktail.name %> </h1>
  <%= simple_form_for [ @cocktail, @dose ] do |f| %>
    <%= f.association :ingredient, collection: Ingredient.all %>
    <%= f.input :description %>
        <%= f.submit "Add a new dose", :class => "btn btn-flat"  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "Cocktail Generator" , cocktails_path, :class => "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Generate a cocktail" , new_cocktail_path(Cocktail.new()), :class => "btn btn-flat" %>
      </li>

    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>